### ISSUE TITLE
Not working on watch

### ISSUE THREAD

**Issue by Mgreen166** [leptos-null/MonthDay#2]
I updated to iphone15+ and the app does not show on watch or phone. In the App Store it shows purchased and can not do anything with it.
Can you help with this problem?

**Comment by leptos-null** [comment]
Thanks for opening an issue. I’ve seen a few of these reports, unfortunately it sounds like an iOS/ watchOS issue that the app doesn’t show up at all.

**Comment by Mgreen166** [comment]
I got it fixed had to redownload it thru the watch not on the phone

Michael Green
708-733-2474

________________________________

**Comment by leptos-null** [comment]
Oh, this is great news. Thank you very much for sharing your solution, I will pass this on to others.
